//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Drawing;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace SedimentTrap.Properties {
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("SedimentTrap.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Arrow {
            get {
                object obj = ResourceManager.GetObject("Arrow", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Arrow_48px {
            get {
                object obj = ResourceManager.GetObject("Arrow_48px", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Capture {
            get {
                object obj = ResourceManager.GetObject("Capture", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string ComunicacionArduino_EEPROM_Read_Click_Error {
            get {
                return ResourceManager.GetString("ComunicacionArduino_EEPROM_Read_Click_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elija antes un puerto COM.
        /// </summary>
        public static string ComunicacionArduino_MensajeErrorCom_Elija_antes_un_puerto_COM {
            get {
                return ResourceManager.GetString("ComunicacionArduino_MensajeErrorCom_Elija_antes_un_puerto_COM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al elegir un puerto.
        /// </summary>
        public static string ComunicacionArduino_MensajeErrorCom_Error_al_elegir_un_puerto {
            get {
                return ResourceManager.GetString("ComunicacionArduino_MensajeErrorCom_Error_al_elegir_un_puerto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elija una fecha adecuada.
        /// </summary>
        public static string ComunicacionArduino_MensajeErrorFechaMenor_Elija_una_fecha_adecuada {
            get {
                return ResourceManager.GetString("ComunicacionArduino_MensajeErrorFechaMenor_Elija_una_fecha_adecuada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número máximo de muestras es 21.
        /// </summary>
        public static string ComunicacionArduino_MensajeErrorMuestras_El_número_máximo_de_muestras_es_21 {
            get {
                return ResourceManager.GetString("ComunicacionArduino_MensajeErrorMuestras_El_número_máximo_de_muestras_es_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pueden elegir mas muestras.
        /// </summary>
        public static string ComunicacionArduino_MensajeErrorMuestras_No_se_pueden_elegir_mas_muestras {
            get {
                return ResourceManager.GetString("ComunicacionArduino_MensajeErrorMuestras_No_se_pueden_elegir_mas_muestras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número mínimo de muestras es cero.
        /// </summary>
        public static string ComunicacionArduino_MensajeErrorMuestrasCero_El_número_mínimo_de_muestras_es_cero {
            get {
                return ResourceManager.GetString("ComunicacionArduino_MensajeErrorMuestrasCero_El_número_mínimo_de_muestras_es_cero" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elija un número adecuado.
        /// </summary>
        public static string ComunicacionArduino_MensajeErrorMuestrasCero_Elija_un_número_adecuado {
            get {
                return ResourceManager.GetString("ComunicacionArduino_MensajeErrorMuestrasCero_Elija_un_número_adecuado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elija un puerto adecuado.
        /// </summary>
        public static string ComunicacionArduino_MensajeErrorPuertoInvalido_Elija_un_puerto_adecuado {
            get {
                return ResourceManager.GetString("ComunicacionArduino_MensajeErrorPuertoInvalido_Elija_un_puerto_adecuado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puerto no válido.
        /// </summary>
        public static string ComunicacionArduino_MensajeErrorPuertoInvalido_Puerto_no_válido {
            get {
                return ResourceManager.GetString("ComunicacionArduino_MensajeErrorPuertoInvalido_Puerto_no_válido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Muestra .
        /// </summary>
        public static string ComunicacionArduino_NumeraMuestras_Muestra_ {
            get {
                return ResourceManager.GetString("ComunicacionArduino_NumeraMuestras_Muestra_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El led está encendido.
        /// </summary>
        public static string ComunicacionArduino_ON_Click_El_led_está_encendido {
            get {
                return ResourceManager.GetString("ComunicacionArduino_ON_Click_El_led_está_encendido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap config {
            get {
                object obj = ResourceManager.GetObject("config", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ic_adjust_black_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_adjust_black_48dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ic_error_red_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_error_red_48dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ic_error_red_48dp1 {
            get {
                object obj = ResourceManager.GetObject("ic_error_red_48dp1", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ic_ok_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_ok_48dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ic_warning_amber_48dp {
            get {
                object obj = ResourceManager.GetObject("ic_warning_amber_48dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icml {
            get {
                object obj = ResourceManager.GetObject("icml", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap IMG_20160612_194149089_HDR {
            get {
                object obj = ResourceManager.GetObject("IMG_20160612_194149089_HDR", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap left10 {
            get {
                object obj = ResourceManager.GetObject("left10", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap left20 {
            get {
                object obj = ResourceManager.GetObject("left20", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fechas de control de la trampa de sedimentos
        ///
        ///Instituto de Ciencias del Mar y Limnologia, UNAM
        ///
        ///Fecha de creacion del archivo: 
        ///10/08/2016 11:48:16 p.m.
        ///
        ///Lista de fechas programadas en la trampa de sedimentos
        ///1) 10/08/2016
        ///2) 13/08/2016
        ///3) 01/09/2016
        ///4) 29/09/2016
        ///5) 21/10/2016
        ///6) 11/11/2016
        ///7) 09/12/2016
        ///.
        /// </summary>
        public static string logfile {
            get {
                return ResourceManager.GetString("logfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap OFF {
            get {
                object obj = ResourceManager.GetObject("OFF", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ok_png {
            get {
                object obj = ResourceManager.GetObject("ok_png", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap ON {
            get {
                object obj = ResourceManager.GetObject("ON", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap right10 {
            get {
                object obj = ResourceManager.GetObject("right10", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap right20 {
            get {
                object obj = ResourceManager.GetObject("right20", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Stop01 {
            get {
                object obj = ResourceManager.GetObject("Stop01", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  Revise la cantidad de muestras que quiere almacer.
        /// </summary>
        public static string txt_revise_fechas {
            get {
                return ResourceManager.GetString("txt_revise_fechas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al almacenar las fechas.
        /// </summary>
        public static string txt_title_error_fechas {
            get {
                return ResourceManager.GetString("txt_title_error_fechas", resourceCulture);
            }
        }
    }
}
